### ISSUE TITLE
preset.ymlでhostを変更した場合の更新について

### ISSUE THREAD

**Issue by ftakao2007** [koutyan/Symbol-Node-Updater#1]
便利なツールの開発お疲れ様です。
一点気づいた事がありますのでissueを上げさせていただきました。

滅多にあることでは無いと思うのですが、preset.ymlのhostを更新した場合はsymbol-bootstrap compose --upgradeを実行しないとtarget/docker/docker-compose.ymlのnodeのhostname等の設定が以前のままになってしまいそうです。

![image](https://user-images.githubusercontent.com/3776879/117514299-7a9a7a00-afce-11eb-816e-0ab16fae1008.png)

preset.ymlを変更せず単にbootstrapのバージョンを上げるだけの場合は特に必要無いとは思うのですが、
ご参考までに共有させていただきました。よろしくお願い致します。

**Comment by koutyan** [comment]
ご報告ありがとうございます。
Symbolノード更新時に、プリセットファイルを更新している場合に正しく動作するように修正した Version 1.0.1 をリリースいたしました。よって、このIssueはCloseさせていただきます。
