### ISSUE TITLE
手順4実行後にFatal発生

### ISSUE THREAD

**Issue by NodaKeisuke** [koutyan/Symbol-Node-Updater#2]
便利なツールを開発頂きありがとうございます。
手順4実行後にFatailのメッセージが発生してしまい、原因がわからず申し訳ありませんが、サポートをいただけますでしょうか？

■エラー該当箇所
TASK [Make directory for https] ************************************************
task path: /home/ubuntu/Symbol-Node-Builder-1.0.1/playbook.yml:156
fatal: [localhost]: FAILED! => {
    "msg": "The conditional check 'https_node == true' failed. The error was: error while evaluating conditional (https_node == true): 'https_node' is undefined\n\nThe error appears to be in '/home/ubuntu/Symbol-Node-Builder-1.0.1/playbook.yml': line 156, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Make directory for https\n      ^ here\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=25   changed=9    unreachable=0    failed=1    skipped=1    rescued=0    ignored=1   

ubuntu@ik1-314-17087:~/Symbol-Node-Builder-1.0.1$

**Comment by koutyan** [comment]
こちら、「Symbol Node Builder」における問題報告という認識です。そのため、「Symbol Node Builder」の方のIssueに再度投稿していただけますでしょうか。

お手数おかけしますがよろしくお願いいたします。

**Comment by NodaKeisuke** [comment]
ご返信ありがとうございます。
手順は「Symbol Node Updater」の手順を実行したのですが、ディレクトリを誤って「Symbol-Node-Builder-1.0.1」で実行してしまったのでしょうか？以下が手順１を実行した際のログです。


wget https://github.com/koutyan/Symbol-Node-Updater/archive/refs/tags/v1.0.1.tar.gz
--2021-06-12 01:41:25--  https://github.com/koutyan/Symbol-Node-Updater/archive/refs/tags/v1.0.1.tar.gz
Resolving github.com (github.com)... 52.69.186.44
Connecting to github.com (github.com)|52.69.186.44|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/koutyan/Symbol-Node-Updater/tar.gz/refs/tags/v1.0.1 [following]
--2021-06-12 01:41:26--  https://codeload.github.com/koutyan/Symbol-Node-Updater/tar.gz/refs/tags/v1.0.1
Resolving codeload.github.com (codeload.github.com)... 13.112.159.149
Connecting to codeload.github.com (codeload.github.com)|13.112.159.149|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v1.0.1.tar.gz.1’

v1.0.1.tar.gz.1         [<=>                 ]       0  --.-KB/s               v1.0.1.tar.gz.1         [ <=>                ]   5.75K  --.-KB/s    in 0s      

2021-06-12 01:41:26 (73.6 MB/s) - ‘v1.0.1.tar.gz.1’ saved [5884]

ubuntu@ik1-314-17087:~$ ll
total 84
drwxr-xr-x 8 ubuntu ubuntu  4096 Jun 12 01:41 ./
drwxr-xr-x 3 root   root    4096 Oct 30  2020 ../
drwxrwxr-x 4 ubuntu ubuntu  4096 May  7 22:38 .ansible/
-rw------- 1 ubuntu ubuntu  3049 May 30 21:25 .bash_history
-rw-r--r-- 1 ubuntu ubuntu   220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu  3771 Feb 25  2020 .bashrc
drwx------ 2 ubuntu ubuntu  4096 May  7 22:34 .cache/
-rw-r--r-- 1 ubuntu ubuntu   807 Feb 25  2020 .profile
drwx------ 2 ubuntu ubuntu  4096 May  7 22:38 .ssh/
-rw-r--r-- 1 ubuntu ubuntu     0 May  7 22:37 .sudo_as_admin_successful
-rw------- 1 ubuntu ubuntu 13887 May 10 12:49 .viminfo
-rw-rw-r-- 1 ubuntu ubuntu   209 Jun 12 01:41 .wget-hsts
drwxrwxr-x 4 ubuntu ubuntu  4096 May  7 19:07 Symbol-Node-Builder-1.0.1/
drwxrwxr-x 2 ubuntu ubuntu  4096 May  8 01:51 https-portal/
drwxrwxr-x 3 ubuntu ubuntu  4096 May  7 22:43 symbol-bootstrap/
-rw-rw-r-- 1 ubuntu ubuntu  7284 May  7 22:34 v1.0.1.tar.gz
-rw-rw-r-- 1 ubuntu ubuntu  5884 Jun 12 01:41 v1.0.1.tar.gz.1
ubuntu@ik1-314-17087:~$ 
ubuntu@ik1-314-17087:~$ 
ubuntu@ik1-314-17087:~$ tar xzvf v1.0.1.tar.gz && rm v1.0.1.tar.gz
Symbol-Node-Builder-1.0.1/
Symbol-Node-Builder-1.0.1/README.md
Symbol-Node-Builder-1.0.1/ansible.cfg
Symbol-Node-Builder-1.0.1/conf/
Symbol-Node-Builder-1.0.1/conf/inventory
Symbol-Node-Builder-1.0.1/conf/preset.yml
Symbol-Node-Builder-1.0.1/conf/vars.yml
Symbol-Node-Builder-1.0.1/playbook.yml
Symbol-Node-Builder-1.0.1/setup.sh
Symbol-Node-Builder-1.0.1/templates/
Symbol-Node-Builder-1.0.1/templates/https_docker-compose.j2
ubuntu@ik1-314-17087:~$ cd Symbol-Node-Updater-1.0.1/
-bash: cd: Symbol-Node-Updater-1.0.1/: No such file or directory
ubuntu@ik1-314-17087:~$ ll

**Comment by NodaKeisuke** [comment]
原因がわかりました。解凍に失敗しており、Builderの方で実行してしまったことが原因でした。深夜に大変失礼しました。本件、クローズしていただいて大丈夫です。

**Comment by koutyan** [comment]
なるほどです。以前にBuilderをダウンロードしたもの(`v1.0.1.tar.gz`)を消し忘れた結果、Updaterをダウンロードしたときにファイル名が変わってしまい(`v1.0.1.tar.gz.1`)、Builderの方(`v1.0.1.tar.gz`)を解凍してしまっていたようですね。

原因が判明して良かったです。

これをもって、本件Closeいたします。
